<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <title>{{ __('Analytics Report') }}</title>
    <style>
        body { font-family: 'dejavu sans', sans-serif; font-size: 14px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; }
        .header h1 { margin: 0; font-size: 24px; color: #1e3a8a; }
        .header p { color: #6b7280; font-size: 12px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #e5e7eb; padding: 10px; text-align: right; }
        th { background-color: #f3f4f6; color: #374151; font-weight: bold; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 10px; color: #9ca3af; padding: 10px 0; border-top: 1px solid #e5e7eb; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ __('Dashboard Analytics Report') }}</h1>
        <p>{{ __('Period') }}: {{ __(ucfirst($data['period'])) }} | {{ __('Date') }}: {{ now()->format('Y-m-d H:i') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>{{ __('Metric') }}</th>
                <th>{{ __('Value') }}</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ __('Total Registered Parents') }}</td>
                <td>{{ $data['total_registered_parents'] }}</td>
            </tr>
            <tr>
                <td>{{ __('Active Children Profiles') }}</td>
                <td>{{ $data['active_children_profiles'] }}</td>
            </tr>
            <tr>
                <td>{{ __('Active Subscription Plans') }}</td>
                <td>{{ $data['active_subscription_plans'] }}</td>
            </tr>
            <tr>
                <td>{{ __('Executed Therapy Sessions') }}</td>
                <td>{{ $data['executed_therapy_sessions'] }}</td>
            </tr>
            <tr>
                <td>{{ __('Average Progress Percentage') }}</td>
                <td>{{ $data['average_progress_percentage'] }}</td>
            </tr>
            <tr>
                <td>{{ __('Total Revenue (SAR)') }}</td>
                <td>{{ number_format($data['total_revenue_sar'], 2) }}</td>
            </tr>
        </tbody>
    </table>

    <div class="footer">
        {{ __('Generated by') }} {{ config('app.name') }} &copy; {{ date('Y') }}
    </div>
</body>
</html>
